WebMvc/ViewModels/PaymentInfoViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMvc.Models;

namespace WebMvc.ViewModels
{
    public class PaymentInfoViewModel
    {
        public Cart Cart { get; set; }

        public int PaymentType { get; set; }
    }
}

WebMvc/Controllers/PaymentInfoController.cs
using System;
using Microsoft.AspNetCore.Mvc;
using WebMvc.Models;
using WebMvc.ViewModels;

namespace WebMvc.Controllers
{
    public class PaymentInfoController : Controller
    {
        private readonly Cart _cart;

        public PaymentInfoController(Cart cart)
        {
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View(new PaymentInfoViewModel
            {
                Cart = _cart
            });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult AddPaymentInformation(PaymentInfoViewModel viewModel)
        {
            // Ελέγχουμε την εγγυρότητα των δεδομένων. Ο χρήστης είναι υποχρεώμένος να συμπληρώσει τρόπο πληρώμης
            if (!ModelState.IsValid)
            {
                return RedirectToAction("Index");
            }

            return RedirectToAction("AddOrder","Order", new {paymentType = viewModel.PaymentType});

        }
    }
}

WebMvc/Views/PaymentInfo/Index.cshtml
@model WebMvc.ViewModels.PaymentInfoViewModel
@{
    ViewBag.Title = "Πληροφορίες Πληρωμής | Cannature";
    ViewBag.PageTitle = "CHECKOUT";
}
<div class="container page-wrap">
    <div class="row checkout-steps">
        <div class="col-xs-4 fadeUpEffect">
            <a href="@Url.Action("Index", "CheckoutInfo")">
                <div class="row">
                    <div class="col-sm-2"><span>1</span></div>
                    <div class="col-sm-10">
                        <p>ΠΛΗΡΟΦΟΡΙΕΣ<br />ΠΑΡΑΓΓΕΛΙΑΣ</p>
                    </div>
                </div>
            </a>
        </div>


        <div class="col-xs-4 fadeUpEffect2 wait07s active">
            <div class="row">
                <div class="col-sm-2"><span>2</span></div>
                <div class="col-sm-10">
                    <p>ΠΛΗΡΟΦΟΡΙΕΣ<br />ΠΛΗΡΩΜΗΣ</p>
                </div>
            </div>
        </div>

    </div>
    <form asp-action="AddPaymentInformation" asp-controller="PaymentInfo" method="post">
        <span asp-validation-for="PaymentType" class="field-validation-error"></span>
        <div id="products" class="row cart-boxes">
            <div class="col-sm-12 fadeUpEffect2 wait07s ">
                <div class="checkout-cart">
                    <h3 class="text-center">Προιόντα</h3>
                    <table class="table">

                        <tr class="hidden-xs hidden-sm">
                            <td>ΠΡΟΪΟΝ</td>
                            <td>ΤΙΜΗ</td>
                            <td>ΠΟΣΟΤΗΤΑ</td>
                            <td>ΣΥΝΟΛΟ</td>
                            <td></td>
                        </tr>
                        @{
                            foreach (var line in Model.Cart.LineCollection)
                            {
                                <tr>
                                    <td class="td-title">
                                        @line.ProductName
                                    </td>
                                    @{

                                            <td class="td-half"><b class="hidden-md hidden-lg">ΤΙΜΗ<br /></b>&euro; @line.Price.ToString("0.00")</td>
                                            <td class="td-half">
                                                <b class="hidden-md hidden-lg">ΠΟΣΟΤΗΤΑ<br /></b>
                                                @line.Quantity
                                            </td>
                                            <td class="td-half">
                                                <b class="hidden-md hidden-lg">ΣΥΝΟΛΟ<br /></b>
                                                &euro; @((line.Quantity * line.Price).ToString("0.00"))</td>

                                    }
                                    <td align></td>
                                </tr>
                            }
                        }
                    </table>
                </div>
            </div>
        </div>
        <div class="row cart-boxes">

            <div class="col-sm-6 fadeUpEffect2 wait09s">
                <div>
                    <h3 class="text-center">Tρόποι Πληρωμής</h3>
                    <div>
                        <div class="radio-btn">
                            @Html.RadioButtonFor(m => m.PaymentType, "1", new { @type = "radio", @name = "payment", @id = "uncheckRadio1" })
                            <label for="uncheckRadio1">
                                <span><i class="fa fa-check"></i></span>
                                Αντικαταβολή
                            </label>
                        </div>
                    </div>
                    <div>
                        <div class="radio-btn">
                            @Html.RadioButtonFor(m => m.PaymentType, "2", new { @type = "radio", @name = "payment", @id = "uncheckRadio2" })
                            <label for="uncheckRadio2">
                                <span><i class="fa fa-check"></i></span>
                                Paypal
                            </label>
                        </div>
                    </div>
                </div>
            </div>

            <div class="col-sm-6 fadeUpEffect2 wait09s">
                <div>
                    <h3>Σύνολο</h3>
                    <table class="data-table">
                        <tr>
                            <td>Υποσύνολο</td>
                            <td class="td-detail">&euro; @Model.Cart.ComputeTotalValue().ToString("0.00") </td>
                        </tr>
                        <tr>
                            <td>Μεταφορικά</td>
                            <td class="td-detail">&euro; 0</td>
                        </tr>

                        <tr>
                            <td colspan="2">
                                <div class="black-line"></div>
                            </td>
                        </tr>

                        <tr>
                            <td>Σύνολο</td>
                            <td class="td-detail"> &euro; @((Model.Cart.ComputeTotalValue()).ToString("0.00")) </td>
                        </tr>
                    </table>

                </div>
            </div>

            <div class="col-sm-4 col-sm-offset-8 t-center">
                <h3></h3>
                <button type="post" class="button">ΟΛΟΚΛΗΡΩΣΗ ΠΑΡΑΓΓΕΛΙΑΣ</button>
                <br />
            </div>


        </div>
    </form>
</div>