WebMvc/Models/Product.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace WebMvc.Models
{
    public class Product
    {
        public int ProductId { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public string BulletDescription { get; set; }

        public int CategoryId { get; set; }

        public int BrandId{ get; set; }

        public bool IsBest { get; set; }

        public bool HasStock { get; set; }

        public List<Picture> Pictures { get; set; }

        public List<ProductVersion> Versions { get; set; }



    }
}

WebMvc/ViewModels/ProductViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using WebMvc.Models;

namespace WebMvc.ViewModels
{
    public class ProductViewModel
    {
        public int Id { get; set; }

        public string Name { get; set; }

        public string Description { get; set; }

        public int CategoryId { get; set; }

        public int BrandId { get; set; }

        public bool IsBest { get; set; }

        public IEnumerable<Category> Categories { get; set; }

        public IEnumerable<Brand> Brands { get; set; }

    }
}

WebMvc/ViewModels/ProductsViewModel.cs
using System.Collections.Generic;
using WebMvc.Models;

namespace WebMvc.ViewModels
{
    public class ProductsViewModel
    {
        public int PageIndex { get; set; }
        public int PageSize { get; set; }
        public int TotalPages { get; set; }
        public List<ProductSummary> Data { get; set; }
    }
}

WebMvc/Controllers/CartController.cs
using System;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using WebMvc.Models;
using WebMvc.Services;
using WebMvc.ViewModels;

namespace WebMvc.Controllers
{
    public class CartController : Controller
    {

        private readonly ICatalogService _catalogService;
        private readonly Cart _cart;

        public CartController( ICatalogService catalogService, Cart cart)
        {
            _catalogService = catalogService;
            _cart = cart;
        }

        public async Task<RedirectToActionResult> AddToCart(int productId, string returnUrl, int productVersionId, int quantity = 1)
        {
            // Βρίσκω το προϊον απο το productId και productVersionId
            var product = await _catalogService.GetProductData(productId);

            // Βρισκώ την παρούσα έκδοση
            var currentProductVersion = product.Versions.SingleOrDefault(v => v.Id == productVersionId && v.HasStock);

            // Εχω stock οπότε έχει νοήμα να προχωρήσω
            if (currentProductVersion != null)
            {
                await _cart.AddItem(productId, productVersionId, product.Name,
                        product.Pictures.SingleOrDefault(p => p.PictureTypeId == Picture.IsMainPhoto)?.ThumbnailPictureUri,
                        quantity, currentProductVersion.GetPrice );
            }

            return RedirectToAction("Index", new {returnUrl});
        }

        public async Task<RedirectToActionResult> RemoveFromCart(int productId, int productVersionId, string returnUrl)
        {
            var cartLine = _cart.LineCollection.SingleOrDefault(l => l.ProductId == productId && l.ProductVersionId == productVersionId);

            if (cartLine != null)
            {
                await _cart.RemoveItem(cartLine.ProductId, cartLine.ProductVersionId);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public async Task<RedirectToActionResult> UpdateCart(IFormCollection formCollection, string returnUrl)
        {
            // Για κάθε αντικείμενο στο καλάθι ενημερώνω τον αριθμο των προϊλοντων.
            foreach (var line in _cart.LineCollection)
            {
                int newQuantity = int.Parse(formCollection[String.Concat(line.ProductId,line.ProductVersionId)]);
                await _cart.UpdateItemQuantity(line.ProductId, line.ProductVersionId, newQuantity);
            }

            return RedirectToAction("Index", new { returnUrl });
        }

        public RedirectToActionResult ClearCart(string returnUrl)
        {
            _cart.Clear();

            return RedirectToAction("Index", new {returnUrl});
        }


        public IActionResult Index(string returnUrl)
        {
            return View(new CartIndexViewModel
            {
                Cart = _cart,
                ReturnUrl = returnUrl
            });
        }
    }
}

WebMvc/Controllers/ProductController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebMvc.Services;
using WebMvc.ViewModels;

namespace WebMvc.Controllers
{
    public class ProductController : Controller
    {
        private readonly ICatalogService _service;

        public ProductController(ICatalogService service)
        {
            _service = service;
        }

        public async Task<IActionResult> Index(int id, int productVersionId)
        {
            var product = await _service.GetProductData(id);

            return View(new ProductPageViewModel {ProductVersionId = productVersionId, Product = product, Quantity = 1});
        }
    }
}

WebMvc/Views/Product/Index.cshtml
@using System.IO
@using System.Text.RegularExpressions
@using Microsoft.AspNetCore.Http.Extensions
@using WebMvc.Models
@model WebMvc.ViewModels.ProductPageViewModel
@{

    var product = @Model.Product;
    var currentVersion = @Model.Product.Versions.SingleOrDefault(v => v.Id == @Model.ProductVersionId);
    var productPhotos = @Model.Product.Pictures;

    string[] stringSeparators = new string[] { ".", ";", "!" };
    string[] descriptionArray = product.Description.Split(stringSeparators, StringSplitOptions.None);
    string description = (descriptionArray == null) ? product.Name : Regex.Replace(descriptionArray[0] + ".", "<.*?>|&.*?;", string.Empty).Trim(); ;

    if (descriptionArray != null && descriptionArray.Length > 1)
    {
        description = Regex.Replace(descriptionArray[0] + ". " + descriptionArray[1] + ".", "<.*?>|&.*?;", string.Empty).Trim();
    }

    ViewBag.Title = product.Name + " | Cannature";
    ViewBag.Description = description;
    ViewBag.PageTitle = "Περιγραφή Προϊοντος";
}


<div class="page-slider p-product" style="background-image:url(images/content/prd_page02.jpg);"><div class="overlay slider-overlay"></div></div>

<div class="wrap">
    <div class="container-fluid">
        <div class="row">

            <div class="col-md-12">
                <div class="prd-page-info">
                    <h1 class="product-title">@product.Name</h1>

                    @{
                        if (currentVersion?.Discount != 0)
                        {
                            <div class="prd-info-price big">
                                @(Math.Round(currentVersion.InitialPrice - (currentVersion.Discount * currentVersion.InitialPrice), 2).ToString("0.00")) &euro;
                                <span class="prd-info-discount">@Math.Round(currentVersion.InitialPrice, 2).ToString("0.00") &euro;</span> <span class="prd-info-percent"> @(currentVersion.Discount * 100)%</span>
                            </div>
                        }
                        else
                        {
                            <div class="prd-info-price big">
                                @Math.Round(currentVersion.InitialPrice, 2).ToString("0.00") &euro;
                            </div>
                        }
                    }


                    @{
                        var hideCart = "";
                        var hideBan = "";


                        if (!currentVersion.HasStock)
                        {
                            hideCart = "hide-cart";
                            hideBan = "";
                        }
                        else
                        {
                            hideCart = "";
                            hideBan = "hide-ban";
                        }

                        <div class="row">
                            @{

                                        <div class="col-md-6">
                                            <form id="version-select" asp-action="Index" asp-controller="Product" asp-route-Id="@Model.Product.ProductId" method="get">
                                                <select class="form-control version-select" onchange="$('#version-select').submit()" asp-for="@Model.ProductVersionId" asp-items="@(new SelectList(product.Versions, "Id", "Specification"))">
                                                </select>
                                            </form>
                                        </div>

                            }
                            <form id="product-quantity" asp-action="AddToCart" asp-controller="Cart" asp-route-productId="@Model.Product.ProductId" asp-route-quantity="@Model.Quantity" asp-route-productVersionId="@Model.ProductVersionId" asp-route-returnUrl="@ViewContext.HttpContext.Request.GetEncodedPathAndQuery()">
                                <div class="col-md-6">
                                    <div class="spinner">
                                        <input asp-for="Quantity" class="form-control quantity-text-box" min="1" max="100" type="text" />
                                        <div class="input-group-btn-vertical">
                                            <button class="btn btn-default btn-minus" type="button"><i class="fa fa-minus"></i></button>
                                            <button class="btn btn-default" type="button"><i class="fa fa-plus"></i></button>
                                        </div>
                                        <br />
                                    </div>
                                </div>
                            </form>

                        </div>
                    }

                    @{



                        <div class="row">
                            <div class="col-md-6">
                                <div class="prd-page-cart-container">
                                    <button type="submit" class="prd-page-cart @hideCart" onclick="$('#product-quantity').submit()">
                                        @Html.Raw(File.ReadAllText("wwwroot/svg/cart.svg"))
                                        <span>ΣΤΟ<br />ΚΑΛΑΘΙ</span>
                                    </button>

                                    <a class="prd-page-cart @hideBan">
                                        <?xml version="1.0" ?>

                                        <?xml version="1.0" ?>

                                        <svg class="icon-svg" version="1.1" viewBox="0 0 24 24" xmlns="http://www.w3.org/2000/svg" xmlns:sketch="http://www.bohemiancoding.com/sketch/ns" xmlns:xlink="http://www.w3.org/1999/xlink"><title /><desc /><defs /><g fill="none" fill-rule="evenodd" id="miu" stroke="none" stroke-width="1"><g id="Artboard-1" transform="translate(-863.000000, -119.000000)"><g id="slice" transform="translate(215.000000, 119.000000)" /><path d="M868.437303,122.730196 C870.30228,121.033947 872.780394,120 875.5,120 C881.29899,120 886,124.70101 886,130.5 C886,133.219606 884.966053,135.69772 883.269804,137.562697 L868.437303,122.730196 Z M867.730196,123.437303 C866.033947,125.30228 865,127.780394 865,130.5 C865,136.29899 869.70101,141 875.5,141 C878.219606,141 880.69772,139.966053 882.562697,138.269804 L867.730196,123.437303 Z M864,130.5 C864,124.148725 869.148725,119 875.5,119 C881.851275,119 887,124.148725 887,130.5 C887,136.851275 881.851275,142 875.5,142 C869.148725,142 864,136.851275 864,130.5 Z" fill="#fff" id="circle-no-forbidden-outline-stroke" /></g></g></svg>
                                        <span>ΜΗ<br />ΔΙΑΘΕΣΙΜΟ</span>
                                    </a>

                                    <a class="prd-page-cart" asp-action="AddToWishlist" asp-controller="Account" asp-route-productId="@Model.Product.ProductId" asp-route-returnUrl="@ViewContext.HttpContext.Request.GetEncodedPathAndQuery()">
                                        @Html.Raw(File.ReadAllText("wwwroot/svg/heart.svg"))
                                        <span>ΣΤΟ<br />WISHLIST</span>
                                    </a>
                                </div>
                            </div>
                        </div>

                    }
                    <hr />
                </div>

                <div class="col-md-6">
                    <div id="slider-wrap">
                        <div id="slider">
                            <img class="full-width" src=@Url.Content(productPhotos.SingleOrDefault(r => r.PictureTypeId == Picture.IsMainPhoto)?.FullPictureUri ?? "~/images/default-product.png") alt="" />
                            @{
                                foreach (var media in productPhotos.Where(r => r.PictureTypeId == Picture.AreAdditionalPhotos))
                                {
                                    <img class="full-width" src=@Url.Content(media?.FullPictureUri ?? "~/images/default-product.png") alt="" />
                                }

                                foreach (var media in productPhotos.Where(r => r.PictureTypeId == Picture.AreDescriptionPhotos))
                                {
                                    <img class="full-width" src=@Url.Content(media?.FullPictureUri ?? "~/images/default-product.png") alt="" />
                                }
                            }
                        </div>
                        <hr />
                    </div>

                </div>

                <div class="col-md-6">

                    <div class="t-justify">
                        @Html.Raw(@Model.Product.Description)
                    </div>
                </div>
            </div>


        </div>

    </div>
</div>