WebMvc/Controllers/CheckoutInfoController.cs
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using WebMvc.Infrastructure;
using WebMvc.Models;
using WebMvc.ViewModels;

namespace WebMvc.Controllers
{
    public class CheckoutInfoController : Controller
    {
        private readonly Cart _cart;

        public CheckoutInfoController(Cart cart)
        {
            _cart = cart;
        }

        public IActionResult Index()
        {
            return View(_cart.Checkout);
        }

        [ValidateAntiForgeryToken]
        [HttpPost]
        public async Task<IActionResult> AddCheckoutInfo(Checkout checkout)
        {
            // Εαν ο ελέγχος δεν περάσει απο τον server επέστρεψε την φόρμα με τα δεδομένα της μεταβλητής στο Session
            if (!ModelState.IsValid)
            {
                return View("Index", checkout);

            }

            await _cart.UpdateCheckout(checkout);

            return RedirectToAction("Index", "PaymentInfo");
        }




    }
}

WebMvc/Views/CheckoutInfo/Index.cshtml
@model WebMvc.ViewModels.Checkout
@{
    ViewBag.Title = "Πληροφορίες Παραγγελίας | Cannature";
    ViewBag.PageTitle = "CHECKOUT";
}
<div class="container page-wrap">
    <div class="row checkout-steps">
        <div class="col-xs-4 fadeUpEffect active">
            <a href="@Url.Action("Index", "CheckoutInfo")">
                <div class="row">
                    <div class="col-sm-2"><span>1</span></div>
                    <div class="col-sm-10">
                        <p>ΠΛΗΡΟΦΟΡΙΕΣ<br />ΠΑΡΑΓΓΕΛΙΑΣ</p>
                    </div>
                </div>
            </a>
        </div>

        <div class="col-xs-4 fadeUpEffect2 wait07s">
            <div class="row">
                <div class="col-sm-2"><span>2</span></div>
                <div class="col-sm-10">
                    <p>ΠΛΗΡΟΦΟΡΙΕΣ<br />ΠΛΗΡΩΜΗΣ</p>
                </div>
            </div>
        </div>



    </div>
    <form asp-action="AddCheckoutInfo" asp-controller="CheckoutInfo" asp-antiforgery="true" method="post" class="checkout fadeUpEffect3 wait09s">
        <div class="row">
            <div class="col-sm-6">
                <label asp-for="FirstName"></label>
                <span asp-validation-for="FirstName" class="text-danger"></span>
                <input asp-for="FirstName" class="form-control" type="text" placeholder="Όνομα*" />
            </div>
            <div class="col-sm-6">
                <label asp-for="LastName"></label>
                <span asp-validation-for="LastName" class="text-danger"></span>
                <input asp-for="LastName" class="form-control" type="text" placeholder="Έπιθετο*" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="Email"></label>
                <span asp-validation-for="Email" class="text-danger"></span>
                <input asp-for="Email" class="form-control" type="text" placeholder="Email*" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="CompanyName"></label>
                <input asp-for="CompanyName" class="form-control" type="text" placeholder="Όνομα Επιχείρησης" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="PhoneNumber"></label>
                <span asp-validation-for="PhoneNumber" class="text-danger"></span>
                <input asp-for="PhoneNumber" class="form-control" type="text" placeholder="Τηλέφωνο*" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="AddressName"></label>
                <span asp-validation-for="AddressName" class="text-danger"></span>
                <input asp-for="AddressName" class="form-control" type="text" placeholder="Όνομα Διεύθυνσης (Οδός και Αριθμός)*" />
            </div>
            <div class="col-sm-12">
                <label asp-for="AddressAdditionalInfo"></label>
                <span asp-validation-for="AddressAdditionalInfo" class="text-danger"></span>
                <input asp-for="AddressAdditionalInfo" class="form-control" type="text" placeholder="Πληροφοριές Διεύθυνσης" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="AddressCity"></label>
                <span asp-validation-for="AddressCity" class="text-danger"></span>
                <input asp-for="AddressCity" class="form-control" type="text" placeholder="Πόλη*" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="AddressState"></label>
                <input asp-for="AddressState" class="form-control" type="text" placeholder="Νομός*" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="ZipCode"></label>
                <span asp-validation-for="ZipCode" class="text-danger"></span>
                <input asp-for="ZipCode" class="form-control" type="text" placeholder="Ταχυδρομικός Κώδικας*" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <label asp-for="AddressCountry"></label>
                <span asp-validation-for="AddressCountry" class="text-danger"></span>
                <input asp-for="AddressCountry" class="form-control" type="text" placeholder="Χώρα*" />
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12 t-center">
                <button type="post" class="button">ΕΠΟΜΕΝΟ</button>
            </div>
        </div>
    </form>

</div>